# -*- coding: utf-8 -*-
"""main

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/18TJ2_UR0nAsZb0sXlx-6yIYxtZObLKx_
"""

from game_pkg.ballgame import *
game = BallGame()

while True:
    user_input = input("4자리 숫자를 입력하세요 (종료하려면 '종료' 입력): ")

    if user_input.lower() == '종료':
        game.end_game()

    try:
        if ' ' in user_input:
            raise BlankNumber
        if '.' in user_input:
            raise NotInteger
        if '-' in user_input:
            raise NotPositiveInteger

        user_guess = [int(digit) for digit in user_input if digit.isdigit()]
        if len(user_guess) != 4:
            raise NotfFourNumber
        if len(set(user_guess)) < 4:
            raise ValueError("중복 없는 숫자를 입력하세요.")

    except NotInteger:
        print('정수를 입력하세요')
        continue
    except NotPositiveInteger:
        print('양의 정수를 입력하세요')
        continue
    except NotfFourNumber:
        print("4자리인 숫자를 입력하세요.")
        continue
    except BlankNumber:
        print('공백이 없는 숫자를 입력하세요')
        continue
    except ValueError as e:
        print(e)
        continue

    game.play_game(user_guess)
